import { Person } from '../types';

export const initialPerson: Person = {
  id: 'me',
  name: 'Alex Mercer',
  title: 'Self',
  birthYear: '1995',
  parents: [],
  children: [],
  spouses: [],
  generation: 0,
  colorTheme: 'blue',
};

export const demoFamilyTree: Person[] = [
  // Generation -1: Grandparents
  {
    id: 'grandpa-m',
    name: 'Arthur Sterling',
    title: 'Grandfather',
    birthYear: '1935',
    deathYear: '2015',
    isDeceased: true,
    gender: 'male',
    parents: [],
    children: ['father', 'aunt'],
    spouses: ['grandma-m'],
    generation: -1,
    colorTheme: 'slate',
  },
  {
    id: 'grandma-m',
    name: 'Eleanor Sterling',
    title: 'Grandmother',
    birthYear: '1938',
    isDeceased: false,
    gender: 'female',
    parents: [],
    children: ['father', 'aunt'],
    spouses: ['grandpa-m'],
    generation: -1,
    colorTheme: 'slate',
  },

  // Generation 0: Parents, Spouses, and Aunts/Uncles
  {
    id: 'father',
    name: 'Robert Sterling',
    title: 'Father',
    birthYear: '1965',
    isDeceased: false,
    gender: 'male',
    parents: ['grandpa-m', 'grandma-m'],
    children: ['me', 'sister'],
    spouses: ['mother'],
    generation: 0,
    colorTheme: 'blue',
  },
  {
    id: 'mother',
    name: 'Clara Sterling',
    title: 'Mother',
    birthYear: '1968',
    isDeceased: false,
    gender: 'female',
    parents: [],
    children: ['me', 'sister'],
    spouses: ['father'],
    generation: 0,
    colorTheme: 'rose',
  },
  {
    id: 'aunt',
    name: 'Elizabeth Vance',
    title: 'Aunt',
    birthYear: '1968',
    isDeceased: false,
    gender: 'female',
    parents: ['grandpa-m', 'grandma-m'],
    children: ['cousin-1', 'cousin-2'],
    spouses: ['uncle'],
    generation: 0,
    colorTheme: 'emerald',
  },
  {
    id: 'uncle',
    name: 'David Vance',
    title: 'Uncle (by Marriage)',
    birthYear: '1966',
    isDeceased: false,
    gender: 'male',
    parents: [],
    children: ['cousin-1', 'cousin-2'],
    spouses: ['aunt'],
    generation: 0,
    colorTheme: 'slate',
  },

  // Generation 1: Me, Sibling, and Cousins
  {
    id: 'me',
    name: 'Alex Mercer',
    title: 'Self',
    birthYear: '1995',
    isDeceased: false,
    gender: 'male',
    parents: ['father', 'mother'],
    children: ['daughter'],
    spouses: ['partner'],
    generation: 1,
    colorTheme: 'blue',
  },
  {
    id: 'partner',
    name: 'Sarah Mercer',
    title: 'Spouse',
    birthYear: '1996',
    isDeceased: false,
    gender: 'female',
    parents: [],
    children: ['daughter'],
    spouses: ['me'],
    generation: 1,
    colorTheme: 'rose',
  },
  {
    id: 'sister',
    name: 'Sophia Sterling',
    title: 'Sister',
    birthYear: '1998',
    isDeceased: false,
    gender: 'female',
    parents: ['father', 'mother'],
    children: [],
    spouses: [],
    generation: 1,
    colorTheme: 'violet',
  },
  {
    id: 'cousin-1',
    name: 'Chloe Vance',
    title: 'Cousin',
    birthYear: '1997',
    isDeceased: false,
    gender: 'female',
    parents: ['aunt', 'uncle'],
    children: [],
    spouses: [],
    generation: 1,
    colorTheme: 'emerald',
  },
  {
    id: 'cousin-2',
    name: 'Lucas Vance',
    title: 'Cousin',
    birthYear: '2001',
    isDeceased: false,
    gender: 'male',
    parents: ['aunt', 'uncle'],
    children: [],
    spouses: [],
    generation: 1,
    colorTheme: 'amber',
  },

  // Generation 2: Next Generation
  {
    id: 'daughter',
    name: 'Lily Mercer',
    title: 'Daughter',
    birthYear: '2023',
    isDeceased: false,
    gender: 'female',
    parents: ['me', 'partner'],
    children: [],
    spouses: [],
    generation: 2,
    colorTheme: 'rose',
  }
];
